# Generated by Django 5.2 on 2025-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_request_request_message_id_request_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message_search_id',
            field=models.IntegerField(default=0),
        ),
    ]
