# Generated by Django 5.2.1 on 2025-06-02 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_request_message_search_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfupload',
            name='chat_message_id',
        ),
        migrations.RemoveField(
            model_name='pdfupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='pdfupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='file_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='message_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='path',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='reply_to_message_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
