# Generated by Django 5.2.1 on 2025-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_pdfupload_chat_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='file_id',
            field=models.CharField(default=''),
        ),
    ]
