# Generated by Django 5.2.1 on 2025-06-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_pdfupload_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='state',
            field=models.CharField(choices=[('uploaded', 'uploaded'), ('validated', 'validated')], default='', max_length=25),
        ),
    ]
