# Generated by Django 5.2.1 on 2025-06-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_pdfupload_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='state',
            field=models.CharField(choices=[('uploaded', 'uploaded'), ('validated', 'validated'), ('deleted', 'deleted')], default='', max_length=25),
        ),
    ]
