# Generated by Django 5.2.1 on 2025-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_pdfupload_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='chat_message_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
