# Generated by Django 5.2.1 on 2025-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_notification_chat_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
