# Generated by Django 5.2.1 on 2025-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
