# Generated by Django 5.2.1 on 2025-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_notification_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
