# Generated by Django 5.2.1 on 2025-06-27 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_chatuser_is_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'конфигуряция', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.PositiveBigIntegerField(default=0)),
                ('upload_pdf_count', models.PositiveBigIntegerField(default=0)),
                ('validation_pdf_count', models.PositiveBigIntegerField(default=0)),
                ('deleted_pdf_count', models.PositiveBigIntegerField(default=0)),
                ('subscriptions_for_upload_pdf_count', models.PositiveBigIntegerField(default=0)),
                ('subscriptions_for_validation_pdf_conut', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'счетчик',
                'verbose_name_plural': 'Счетчики',
            },
        ),
    ]
