# Generated by Django 5.2.1 on 2025-06-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_config_options_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='reason',
        ),
    ]
