# Generated by Django 5.2.1 on 2025-06-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_remove_subscription_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='is_in_bot',
        ),
    ]
