# Generated by Django 5.2.1 on 2025-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_remove_chatuser_is_in_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='subscriptions_for_validation_pdf_conut',
        ),
        migrations.AddField(
            model_name='count',
            name='subscriptions_for_validation_pdf_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
