# Generated by Django 5.2.1 on 2025-06-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_remove_count_subscriptions_for_validation_pdf_conut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='subscriptions_for_upload_pdf_count',
        ),
        migrations.RemoveField(
            model_name='count',
            name='subscriptions_for_validation_pdf_count',
        ),
        migrations.RemoveField(
            model_name='count',
            name='upload_pdf_count',
        ),
        migrations.RemoveField(
            model_name='count',
            name='validation_pdf_count',
        ),
        migrations.AddField(
            model_name='count',
            name='subscriptions_for_upload',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='subscriptions_for_validation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='total_upload_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='total_validation_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='upload_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='validation_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
