# Generated by Django 5.2.1 on 2025-06-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_remove_count_subscriptions_for_upload_pdf_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='upload_count',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='validation_count',
        ),
    ]
