# Generated by Django 5.2.1 on 2025-07-01 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Это бот'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='config',
            name='uploads_for_subscription',
            field=models.PositiveIntegerField(default=10, help_text='Количество загрузок pdf, необходимое для подписки'),
        ),
        migrations.AlterField(
            model_name='config',
            name='validations_for_subscription',
            field=models.PositiveIntegerField(default=20, help_text='Количество проверок pdf, необходимое для подписки'),
        ),
        migrations.AlterField(
            model_name='count',
            name='deleted_pdf_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик всех pdf, которые были удалены'),
        ),
        migrations.AlterField(
            model_name='count',
            name='request_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='count',
            name='subscriptions_for_upload',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик подписок за загрузку pdf файлов'),
        ),
        migrations.AlterField(
            model_name='count',
            name='subscriptions_for_validation',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик подписок, полученных за голосование'),
        ),
        migrations.AlterField(
            model_name='count',
            name='total_upload_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик всех pdf файлов, которые загрузил пользователь'),
        ),
        migrations.AlterField(
            model_name='count',
            name='total_validation_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик всех pdf файлов, которые проверил пользователь'),
        ),
        migrations.AlterField(
            model_name='count',
            name='upload_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик загрузок pdf'),
        ),
        migrations.AlterField(
            model_name='count',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='count',
            name='validation_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик проверок пользователя'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chat_id',
            field=models.BigIntegerField(default=0, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chat_message_id',
            field=models.BigIntegerField(default=0, verbose_name='ID сообщения в чате'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('upload', 'загрузка'), ('validation', 'проверка')], max_length=25, verbose_name='Тип: загрузка pdf/проверка pdf'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления из чата'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='file_id',
            field=models.CharField(default='', verbose_name='Уникальный ID файла'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Валидный/Невалидный'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='message_id',
            field=models.BigIntegerField(default=0, verbose_name='ID сообщения'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='path',
            field=models.CharField(default='', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='reply_to_message_id',
            field=models.BigIntegerField(default=0, verbose_name='ID reply сообщения'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='bot.request', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='state',
            field=models.CharField(choices=[('uploaded', 'загружено'), ('validated', 'проверено'), ('deleted', 'удалено')], default='', max_length=25, verbose_name='Сосотояние'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='doi',
            field=models.CharField(max_length=256, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='request',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Дата истечения срока'),
        ),
        migrations.AlterField(
            model_name='request',
            name='message_id',
            field=models.IntegerField(default=0, verbose_name='ID сообщения'),
        ),
        migrations.AlterField(
            model_name='request',
            name='message_search_id',
            field=models.IntegerField(default=0, verbose_name='ID сообщения в чате'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'в ожидании'), ('completed', 'завершенный'), ('expired', 'истекший'), ('removed', 'удаленный')], max_length=25, verbose_name='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='pdf_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='bot.pdfupload', verbose_name='Загруженный pdf файл'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
