# Generated by Django 5.2.1 on 2025-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_alter_chatuser_is_bot_alter_chatuser_join_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterField(
            model_name='validation',
            name='vote',
            field=models.BooleanField(verbose_name='Голос'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата голосования'),
        ),
    ]
