# Generated by Django 5.2.1 on 2025-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_alter_config_options_alter_validation_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'в ожидании'), ('completed', 'завершенный'), ('expired', 'истекший')], max_length=25, verbose_name='Статус запроса'),
        ),
    ]
