# Generated by Django 5.2.1 on 2025-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_alter_config_uploads_for_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='state',
            field=models.CharField(choices=[('uploaded', 'загружено'), ('validated', 'проверено'), ('deleted', 'удалено')], default='', max_length=25, verbose_name='Состояние'),
        ),
    ]
