# Generated by Django 5.2.1 on 2025-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_alter_pdfupload_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='state',
            field=models.CharField(choices=[('uploaded', 'загружено'), ('validated', 'проверено'), ('deleted', 'удалено')], max_length=25, verbose_name='Состояние'),
        ),
    ]
