# Generated by Django 5.2.1 on 2025-07-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_alter_pdfupload_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='uploads_for_subscription',
            field=models.PositiveIntegerField(default='10', help_text='Количество загрузок pdf, необходимое для подписки'),
        ),
        migrations.AlterField(
            model_name='config',
            name='validations_for_subscription',
            field=models.PositiveIntegerField(default='20', help_text='Количество проверок pdf, необходимое для подписки'),
        ),
    ]
